source 'http://rubygems.org'

gem 'selenium-webdriver',       '3.4.0'
gem 'cucumber'
gem 'rspec',                    '3.6.0'
gem 'capybara',                 '2.14.1'
gem 'pry',                      '0.9.10'
gem 'poltergeist',              '1.15.0'
gem 'ffaker'
gem 'report_builder'
gem 'rspec-retry'
gem 'nokogiri'
gem 'json'
gem 'rubytree', git: 'https://github.com/razboev/RubyTree'
gem 'reportportal', git: 'https://github.com/reportportal/agent-ruby.git'
gem 'ruby-oci8'
gem 'httparty'
gem 'rexml'
gem 'xml-simple'
gem 'geckodriver-helper'
gem 'rest-client'
gem 'tiny_tds'